In [3]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

Data Preprocessing: Cleaned data by removing unnecessary columns such as Id_no and created a binary target variable and standardized features to have a mean of 0 and a standard deviation of 1.
Model Selection: Chose Random Forest classifier for its robustness, ability to handle non-linear relationships, feature importance insights, and ease of use.

In [4]:
#Loading dataset
col_names = ['Id_No','RI','Na','Mg','Al','Si','K','Ca','Ba','Fe','Type_of_Glass','Binary_type']
df = pd.read_csv('https://raw.githubusercontent.com/FlipRoboTechnologies/ML-Datasets/main/Glass%20Identification/Glass%20Identification.csv',names=col_names, index_col=False)

#Target variable: 0 for window glass (1-4) and 1 for non-window glass (5-7).
df['Binary_type'] = df['Type_of_Glass'].apply(lambda x: 0 if x<=4 else 1)
df

,Id_No,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type_of_Glass,Binary_type
0,1,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.0,1,0
1,2,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.0,1,0
2,3,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.0,1,0
3,4,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.0,1,0
4,5,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.0,7,1
210,211,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.0,7,1
211,212,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.0,7,1
212,213,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.0,7,1
213,214,1.51711,14.23,0.00,2.08,73.36,0.00,8.62,1.67,0.0,7,1

In [5]:
#checking for missing values
df.isnull().sum()

Id_No            0
RI               0
Na               0
Mg               0
Al               0
Si               0
K                0
Ca               0
Ba               0
Fe               0
Type_of_Glass    0
Binary_type      0
dtype: int64

In [6]:
#dropping Id_No column
df = df.drop(columns=['Id_No'])
df

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type_of_Glass,Binary_type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.0,1,0
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.0,1,0
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.0,1,0
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.0,1,0
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
209,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.0,7,1
210,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.0,7,1
211,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.0,7,1
212,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.0,7,1
213,1.51711,14.23,0.00,2.08,73.36,0.00,8.62,1.67,0.0,7,1

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 

#Preprocessing Data
X = df.drop(['Type_of_Glass','Binary_type'], axis=1)
y = df['Binary_type']

#Standardizing the feature
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

#Splitting data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

#Training model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

#Evaluating the model
y_pred = model.predict(X_test)

confu_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
accu_score = accuracy_score(y_test, y_pred)

print(f'Confusion Matrix:{confu_matrix}')
print(f'Classification Report: {class_report}')
print (f'Accuracy Score: {accu_score}')

Confusion Matrix:[[27  1]
 [ 1 14]]
Classification Report:               precision    recall  f1-score   support

           0       0.96      0.96      0.96        28
           1       0.93      0.93      0.93        15

    accuracy                           0.95        43
   macro avg       0.95      0.95      0.95        43
weighted avg       0.95      0.95      0.95        43

Accuracy Score: 0.9534883720930233

In [8]:
#Making Predictions
sample = [[1.617,10.8,1.05,1.20,80.1,0.64,11.5,0.0,0.01]]
sample_scaled = scaler.transform(sample)
prediction = model.predict(sample_scaled)
pred_classification = 'Non-Window Glass' if prediction[0] == 1 else 'Window Glass'

print(f'Predicted type of glass for sample: {pred_classification}')

Predicted type of glass for sample: Non-Window Glass

Trained and evaluated the Random Forest model using metrics such as the confusion matrix, classification report, and accuracy score. The Random Forest model performed well in distinguishing between window glass and non-window glass. In conclusion, the Random Forest classifier effectively handled the dataset's complexity and provided robust, balanced performance on the classification task.